# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game/douniu.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='game/douniu.proto',
    package='',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x11game/douniu.proto\"\xd1\x01\n\x10\x44ouniuCreateRoom\x12\x11\n\tbaseScore\x18\x01 \x01(\x05\x12\x0f\n\x07inScore\x18\x02 \x01(\x05\x12\x12\n\nleaveScore\x18\x03 \x01(\x05\x12\x0e\n\x06sameIp\x18\x04 \x01(\x08\x12\x13\n\x0b\x61utoCompare\x18\x05 \x01(\x08\x12\r\n\x05match\x18\x06 \x01(\x08\x12\x0e\n\x06isGold\x18\x07 \x01(\x08\x12\x0c\n\x04type\x18\x08 \x01(\x05\x12\x0f\n\x07private\x18\t \x01(\x08\x12\x11\n\tgameRules\x18\n \x01(\r\x12\x0f\n\x07\x62\x65tType\x18\x0b \x01(\x05\"\'\n\x13\x44ouniuBankerConfirm\x12\x10\n\x08\x62\x61nkerId\x18\x01 \x01(\x05\"A\n\x0c\x44ouniuRecAsk\x12\x0e\n\x06randId\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x13\n\x0btuiZhuScore\x18\x03 \x01(\x05\"!\n\x10\x44ouniuCardAction\x12\r\n\x05\x63\x61rds\x18\x01 \x03(\x05\"\"\n\x11\x44ouniuScoreAction\x12\r\n\x05score\x18\x01 \x01(\x05\"\xd3\x01\n\x18\x44ouniuPlayerOneSetResult\x12(\n\x07players\x18\x01 \x03(\x0b\x32\x17.DouniuSettlePlayerInfo\x12\x44\n\x10playerGetJackpot\x18\x02 \x03(\x0b\x32*.DouniuPlayerOneSetResult.PlayerGetJackpot\x1aG\n\x10PlayerGetJackpot\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\x0f\n\x07jackpot\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x61rdType\x18\x03 \x01(\x05\"m\n\x16\x44ouniuSettlePlayerInfo\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\x0c\n\x04\x63\x61rd\x18\x02 \x03(\x05\x12\x12\n\ntotalScore\x18\x03 \x01(\x05\x12\r\n\x05score\x18\x04 \x01(\x05\x12\x10\n\x08\x63\x61rdType\x18\x05 \x01(\x05\":\n\x17\x44ouniuReEnterPlayerInfo\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\r\n\x05\x63\x61rds\x18\x02 \x03(\x05\"\xdc\x01\n\x13NiuNiuRecordContent\x12\x0e\n\x06\x62\x61nker\x18\x01 \x01(\x05\x12?\n\rplayerContent\x18\x02 \x03(\x0b\x32(.NiuNiuRecordContent.RecordPlayerContent\x12\x11\n\tgameRules\x18\x03 \x01(\x05\x1a\x61\n\x13RecordPlayerContent\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\r\n\x05\x63\x61rds\x18\x02 \x03(\x05\x12\x14\n\x0cgrabMultiple\x18\x03 \x01(\x05\x12\x13\n\x0bplayedScore\x18\x04 \x01(\x05\x42\x02H\x03\x62\x06proto3')
)

_DOUNIUCREATEROOM = _descriptor.Descriptor(
    name='DouniuCreateRoom',
    full_name='DouniuCreateRoom',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='baseScore', full_name='DouniuCreateRoom.baseScore', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='inScore', full_name='DouniuCreateRoom.inScore', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='leaveScore', full_name='DouniuCreateRoom.leaveScore', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sameIp', full_name='DouniuCreateRoom.sameIp', index=3,
            number=4, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='autoCompare', full_name='DouniuCreateRoom.autoCompare', index=4,
            number=5, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='match', full_name='DouniuCreateRoom.match', index=5,
            number=6, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='isGold', full_name='DouniuCreateRoom.isGold', index=6,
            number=7, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='type', full_name='DouniuCreateRoom.type', index=7,
            number=8, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='private', full_name='DouniuCreateRoom.private', index=8,
            number=9, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='gameRules', full_name='DouniuCreateRoom.gameRules', index=9,
            number=10, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='betType', full_name='DouniuCreateRoom.betType', index=10,
            number=11, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=22,
    serialized_end=231,
)

_DOUNIUBANKERCONFIRM = _descriptor.Descriptor(
    name='DouniuBankerConfirm',
    full_name='DouniuBankerConfirm',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='bankerId', full_name='DouniuBankerConfirm.bankerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=233,
    serialized_end=272,
)

_DOUNIURECASK = _descriptor.Descriptor(
    name='DouniuRecAsk',
    full_name='DouniuRecAsk',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='randId', full_name='DouniuRecAsk.randId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='type', full_name='DouniuRecAsk.type', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='tuiZhuScore', full_name='DouniuRecAsk.tuiZhuScore', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=274,
    serialized_end=339,
)

_DOUNIUCARDACTION = _descriptor.Descriptor(
    name='DouniuCardAction',
    full_name='DouniuCardAction',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='cards', full_name='DouniuCardAction.cards', index=0,
            number=1, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=341,
    serialized_end=374,
)

_DOUNIUSCOREACTION = _descriptor.Descriptor(
    name='DouniuScoreAction',
    full_name='DouniuScoreAction',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='score', full_name='DouniuScoreAction.score', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=376,
    serialized_end=410,
)

_DOUNIUPLAYERONESETRESULT_PLAYERGETJACKPOT = _descriptor.Descriptor(
    name='PlayerGetJackpot',
    full_name='DouniuPlayerOneSetResult.PlayerGetJackpot',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='playerId', full_name='DouniuPlayerOneSetResult.PlayerGetJackpot.playerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='jackpot', full_name='DouniuPlayerOneSetResult.PlayerGetJackpot.jackpot', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cardType', full_name='DouniuPlayerOneSetResult.PlayerGetJackpot.cardType', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=553,
    serialized_end=624,
)

_DOUNIUPLAYERONESETRESULT = _descriptor.Descriptor(
    name='DouniuPlayerOneSetResult',
    full_name='DouniuPlayerOneSetResult',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='players', full_name='DouniuPlayerOneSetResult.players', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='playerGetJackpot', full_name='DouniuPlayerOneSetResult.playerGetJackpot', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_DOUNIUPLAYERONESETRESULT_PLAYERGETJACKPOT, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=413,
    serialized_end=624,
)

_DOUNIUSETTLEPLAYERINFO = _descriptor.Descriptor(
    name='DouniuSettlePlayerInfo',
    full_name='DouniuSettlePlayerInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='playerId', full_name='DouniuSettlePlayerInfo.playerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='card', full_name='DouniuSettlePlayerInfo.card', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='totalScore', full_name='DouniuSettlePlayerInfo.totalScore', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='score', full_name='DouniuSettlePlayerInfo.score', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cardType', full_name='DouniuSettlePlayerInfo.cardType', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=626,
    serialized_end=735,
)

_DOUNIUREENTERPLAYERINFO = _descriptor.Descriptor(
    name='DouniuReEnterPlayerInfo',
    full_name='DouniuReEnterPlayerInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='playerId', full_name='DouniuReEnterPlayerInfo.playerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cards', full_name='DouniuReEnterPlayerInfo.cards', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=737,
    serialized_end=795,
)

_NIUNIURECORDCONTENT_RECORDPLAYERCONTENT = _descriptor.Descriptor(
    name='RecordPlayerContent',
    full_name='NiuNiuRecordContent.RecordPlayerContent',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='playerId', full_name='NiuNiuRecordContent.RecordPlayerContent.playerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cards', full_name='NiuNiuRecordContent.RecordPlayerContent.cards', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='grabMultiple', full_name='NiuNiuRecordContent.RecordPlayerContent.grabMultiple', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='playedScore', full_name='NiuNiuRecordContent.RecordPlayerContent.playedScore', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=921,
    serialized_end=1018,
)

_NIUNIURECORDCONTENT = _descriptor.Descriptor(
    name='NiuNiuRecordContent',
    full_name='NiuNiuRecordContent',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='banker', full_name='NiuNiuRecordContent.banker', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='playerContent', full_name='NiuNiuRecordContent.playerContent', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='gameRules', full_name='NiuNiuRecordContent.gameRules', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_NIUNIURECORDCONTENT_RECORDPLAYERCONTENT, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=798,
    serialized_end=1018,
)

_DOUNIUPLAYERONESETRESULT_PLAYERGETJACKPOT.containing_type = _DOUNIUPLAYERONESETRESULT
_DOUNIUPLAYERONESETRESULT.fields_by_name['players'].message_type = _DOUNIUSETTLEPLAYERINFO
_DOUNIUPLAYERONESETRESULT.fields_by_name['playerGetJackpot'].message_type = _DOUNIUPLAYERONESETRESULT_PLAYERGETJACKPOT
_NIUNIURECORDCONTENT_RECORDPLAYERCONTENT.containing_type = _NIUNIURECORDCONTENT
_NIUNIURECORDCONTENT.fields_by_name['playerContent'].message_type = _NIUNIURECORDCONTENT_RECORDPLAYERCONTENT
DESCRIPTOR.message_types_by_name['DouniuCreateRoom'] = _DOUNIUCREATEROOM
DESCRIPTOR.message_types_by_name['DouniuBankerConfirm'] = _DOUNIUBANKERCONFIRM
DESCRIPTOR.message_types_by_name['DouniuRecAsk'] = _DOUNIURECASK
DESCRIPTOR.message_types_by_name['DouniuCardAction'] = _DOUNIUCARDACTION
DESCRIPTOR.message_types_by_name['DouniuScoreAction'] = _DOUNIUSCOREACTION
DESCRIPTOR.message_types_by_name['DouniuPlayerOneSetResult'] = _DOUNIUPLAYERONESETRESULT
DESCRIPTOR.message_types_by_name['DouniuSettlePlayerInfo'] = _DOUNIUSETTLEPLAYERINFO
DESCRIPTOR.message_types_by_name['DouniuReEnterPlayerInfo'] = _DOUNIUREENTERPLAYERINFO
DESCRIPTOR.message_types_by_name['NiuNiuRecordContent'] = _NIUNIURECORDCONTENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DouniuCreateRoom = _reflection.GeneratedProtocolMessageType('DouniuCreateRoom', (_message.Message,), dict(
    DESCRIPTOR=_DOUNIUCREATEROOM,
    __module__='game.douniu_pb2'
    # @@protoc_insertion_point(class_scope:DouniuCreateRoom)
))
_sym_db.RegisterMessage(DouniuCreateRoom)

DouniuBankerConfirm = _reflection.GeneratedProtocolMessageType('DouniuBankerConfirm', (_message.Message,), dict(
    DESCRIPTOR=_DOUNIUBANKERCONFIRM,
    __module__='game.douniu_pb2'
    # @@protoc_insertion_point(class_scope:DouniuBankerConfirm)
))
_sym_db.RegisterMessage(DouniuBankerConfirm)

DouniuRecAsk = _reflection.GeneratedProtocolMessageType('DouniuRecAsk', (_message.Message,), dict(
    DESCRIPTOR=_DOUNIURECASK,
    __module__='game.douniu_pb2'
    # @@protoc_insertion_point(class_scope:DouniuRecAsk)
))
_sym_db.RegisterMessage(DouniuRecAsk)

DouniuCardAction = _reflection.GeneratedProtocolMessageType('DouniuCardAction', (_message.Message,), dict(
    DESCRIPTOR=_DOUNIUCARDACTION,
    __module__='game.douniu_pb2'
    # @@protoc_insertion_point(class_scope:DouniuCardAction)
))
_sym_db.RegisterMessage(DouniuCardAction)

DouniuScoreAction = _reflection.GeneratedProtocolMessageType('DouniuScoreAction', (_message.Message,), dict(
    DESCRIPTOR=_DOUNIUSCOREACTION,
    __module__='game.douniu_pb2'
    # @@protoc_insertion_point(class_scope:DouniuScoreAction)
))
_sym_db.RegisterMessage(DouniuScoreAction)

DouniuPlayerOneSetResult = _reflection.GeneratedProtocolMessageType('DouniuPlayerOneSetResult', (_message.Message,),
                                                                    dict(

                                                                        PlayerGetJackpot=_reflection.GeneratedProtocolMessageType(
                                                                            'PlayerGetJackpot', (_message.Message,),
                                                                            dict(
                                                                                DESCRIPTOR=_DOUNIUPLAYERONESETRESULT_PLAYERGETJACKPOT,
                                                                                __module__='game.douniu_pb2'
                                                                                # @@protoc_insertion_point(class_scope:DouniuPlayerOneSetResult.PlayerGetJackpot)
                                                                            ))
                                                                        ,
                                                                        DESCRIPTOR=_DOUNIUPLAYERONESETRESULT,
                                                                        __module__='game.douniu_pb2'
                                                                        # @@protoc_insertion_point(class_scope:DouniuPlayerOneSetResult)
                                                                    ))
_sym_db.RegisterMessage(DouniuPlayerOneSetResult)
_sym_db.RegisterMessage(DouniuPlayerOneSetResult.PlayerGetJackpot)

DouniuSettlePlayerInfo = _reflection.GeneratedProtocolMessageType('DouniuSettlePlayerInfo', (_message.Message,), dict(
    DESCRIPTOR=_DOUNIUSETTLEPLAYERINFO,
    __module__='game.douniu_pb2'
    # @@protoc_insertion_point(class_scope:DouniuSettlePlayerInfo)
))
_sym_db.RegisterMessage(DouniuSettlePlayerInfo)

DouniuReEnterPlayerInfo = _reflection.GeneratedProtocolMessageType('DouniuReEnterPlayerInfo', (_message.Message,), dict(
    DESCRIPTOR=_DOUNIUREENTERPLAYERINFO,
    __module__='game.douniu_pb2'
    # @@protoc_insertion_point(class_scope:DouniuReEnterPlayerInfo)
))
_sym_db.RegisterMessage(DouniuReEnterPlayerInfo)

NiuNiuRecordContent = _reflection.GeneratedProtocolMessageType('NiuNiuRecordContent', (_message.Message,), dict(

    RecordPlayerContent=_reflection.GeneratedProtocolMessageType('RecordPlayerContent', (_message.Message,), dict(
        DESCRIPTOR=_NIUNIURECORDCONTENT_RECORDPLAYERCONTENT,
        __module__='game.douniu_pb2'
        # @@protoc_insertion_point(class_scope:NiuNiuRecordContent.RecordPlayerContent)
    ))
    ,
    DESCRIPTOR=_NIUNIURECORDCONTENT,
    __module__='game.douniu_pb2'
    # @@protoc_insertion_point(class_scope:NiuNiuRecordContent)
))
_sym_db.RegisterMessage(NiuNiuRecordContent)
_sym_db.RegisterMessage(NiuNiuRecordContent.RecordPlayerContent)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
