# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game/jinhua.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='game/jinhua.proto',
    package='',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x11game/jinhua.proto\"\x9e\x01\n\x10JinhuaCreateRoom\x12\x11\n\tbaseScore\x18\x01 \x01(\x05\x12\x0f\n\x07inScore\x18\x02 \x01(\x05\x12\x12\n\nleaveScore\x18\x03 \x01(\x05\x12\x0e\n\x06sameIp\x18\x04 \x01(\x08\x12\x10\n\x08gameType\x18\x05 \x01(\x08\x12\x11\n\tgameRules\x18\x06 \x01(\x05\x12\r\n\x05match\x18\x07 \x01(\x08\x12\x0e\n\x06isGold\x18\x08 \x01(\x08\"\'\n\x13JinhuaBankerConfirm\x12\x10\n\x08\x62\x61nkerId\x18\x01 \x01(\x05\"X\n\x0eJinhuaRecRound\x12\x0e\n\x06randId\x18\x01 \x01(\x05\x12\x10\n\x08playerId\x18\x02 \x01(\x05\x12\x12\n\nactionTime\x18\x03 \x01(\x05\x12\x10\n\x08minScore\x18\x04 \x01(\x05\"%\n\x14JinhuaLookCardAction\x12\r\n\x05\x63\x61rds\x18\x01 \x03(\x05\"%\n\x14JinhuaBetScoreAction\x12\r\n\x05score\x18\x01 \x01(\x05\">\n\rJinhuaCompare\x12\x11\n\tcompareId\x18\x01 \x01(\x05\x12\x0b\n\x03win\x18\x02 \x01(\x08\x12\r\n\x05score\x18\x03 \x01(\x05\"D\n\x18JinhuaPlayerOneSetResult\x12(\n\x07players\x18\x01 \x03(\x0b\x32\x17.JinhuaSettlePlayerInfo\"m\n\x16JinhuaSettlePlayerInfo\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\x0c\n\x04\x63\x61rd\x18\x02 \x03(\x05\x12\x12\n\ntotalScore\x18\x03 \x01(\x05\x12\r\n\x05score\x18\x04 \x01(\x05\x12\x10\n\x08\x63\x61rdType\x18\x05 \x01(\x05\":\n\x17JinhuaReEnterPlayerInfo\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\r\n\x05\x63\x61rds\x18\x02 \x03(\x05\"\xb1\x01\n\x13JinhuaRecordContent\x12\x0e\n\x06\x62\x61nker\x18\x01 \x01(\x05\x12?\n\rplayerContent\x18\x02 \x03(\x0b\x32(.JinhuaRecordContent.RecordPlayerContent\x12\x11\n\tgameRules\x18\x03 \x01(\x05\x1a\x36\n\x13RecordPlayerContent\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\r\n\x05\x63\x61rds\x18\x02 \x03(\x05\x42\x02H\x03\x62\x06proto3')
)

_JINHUACREATEROOM = _descriptor.Descriptor(
    name='JinhuaCreateRoom',
    full_name='JinhuaCreateRoom',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='baseScore', full_name='JinhuaCreateRoom.baseScore', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='inScore', full_name='JinhuaCreateRoom.inScore', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='leaveScore', full_name='JinhuaCreateRoom.leaveScore', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sameIp', full_name='JinhuaCreateRoom.sameIp', index=3,
            number=4, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='gameType', full_name='JinhuaCreateRoom.gameType', index=4,
            number=5, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='gameRules', full_name='JinhuaCreateRoom.gameRules', index=5,
            number=6, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='match', full_name='JinhuaCreateRoom.match', index=6,
            number=7, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='isGold', full_name='JinhuaCreateRoom.isGold', index=7,
            number=8, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=22,
    serialized_end=180,
)

_JINHUABANKERCONFIRM = _descriptor.Descriptor(
    name='JinhuaBankerConfirm',
    full_name='JinhuaBankerConfirm',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='bankerId', full_name='JinhuaBankerConfirm.bankerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=182,
    serialized_end=221,
)

_JINHUARECROUND = _descriptor.Descriptor(
    name='JinhuaRecRound',
    full_name='JinhuaRecRound',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='randId', full_name='JinhuaRecRound.randId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='playerId', full_name='JinhuaRecRound.playerId', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='actionTime', full_name='JinhuaRecRound.actionTime', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='minScore', full_name='JinhuaRecRound.minScore', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=223,
    serialized_end=311,
)

_JINHUALOOKCARDACTION = _descriptor.Descriptor(
    name='JinhuaLookCardAction',
    full_name='JinhuaLookCardAction',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='cards', full_name='JinhuaLookCardAction.cards', index=0,
            number=1, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=313,
    serialized_end=350,
)

_JINHUABETSCOREACTION = _descriptor.Descriptor(
    name='JinhuaBetScoreAction',
    full_name='JinhuaBetScoreAction',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='score', full_name='JinhuaBetScoreAction.score', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=352,
    serialized_end=389,
)

_JINHUACOMPARE = _descriptor.Descriptor(
    name='JinhuaCompare',
    full_name='JinhuaCompare',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='compareId', full_name='JinhuaCompare.compareId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='win', full_name='JinhuaCompare.win', index=1,
            number=2, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='score', full_name='JinhuaCompare.score', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=391,
    serialized_end=453,
)

_JINHUAPLAYERONESETRESULT = _descriptor.Descriptor(
    name='JinhuaPlayerOneSetResult',
    full_name='JinhuaPlayerOneSetResult',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='players', full_name='JinhuaPlayerOneSetResult.players', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=455,
    serialized_end=523,
)

_JINHUASETTLEPLAYERINFO = _descriptor.Descriptor(
    name='JinhuaSettlePlayerInfo',
    full_name='JinhuaSettlePlayerInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='playerId', full_name='JinhuaSettlePlayerInfo.playerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='card', full_name='JinhuaSettlePlayerInfo.card', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='totalScore', full_name='JinhuaSettlePlayerInfo.totalScore', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='score', full_name='JinhuaSettlePlayerInfo.score', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cardType', full_name='JinhuaSettlePlayerInfo.cardType', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=525,
    serialized_end=634,
)

_JINHUAREENTERPLAYERINFO = _descriptor.Descriptor(
    name='JinhuaReEnterPlayerInfo',
    full_name='JinhuaReEnterPlayerInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='playerId', full_name='JinhuaReEnterPlayerInfo.playerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cards', full_name='JinhuaReEnterPlayerInfo.cards', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=636,
    serialized_end=694,
)

_JINHUARECORDCONTENT_RECORDPLAYERCONTENT = _descriptor.Descriptor(
    name='RecordPlayerContent',
    full_name='JinhuaRecordContent.RecordPlayerContent',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='playerId', full_name='JinhuaRecordContent.RecordPlayerContent.playerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cards', full_name='JinhuaRecordContent.RecordPlayerContent.cards', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=820,
    serialized_end=874,
)

_JINHUARECORDCONTENT = _descriptor.Descriptor(
    name='JinhuaRecordContent',
    full_name='JinhuaRecordContent',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='banker', full_name='JinhuaRecordContent.banker', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='playerContent', full_name='JinhuaRecordContent.playerContent', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='gameRules', full_name='JinhuaRecordContent.gameRules', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_JINHUARECORDCONTENT_RECORDPLAYERCONTENT, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=697,
    serialized_end=874,
)

_JINHUAPLAYERONESETRESULT.fields_by_name['players'].message_type = _JINHUASETTLEPLAYERINFO
_JINHUARECORDCONTENT_RECORDPLAYERCONTENT.containing_type = _JINHUARECORDCONTENT
_JINHUARECORDCONTENT.fields_by_name['playerContent'].message_type = _JINHUARECORDCONTENT_RECORDPLAYERCONTENT
DESCRIPTOR.message_types_by_name['JinhuaCreateRoom'] = _JINHUACREATEROOM
DESCRIPTOR.message_types_by_name['JinhuaBankerConfirm'] = _JINHUABANKERCONFIRM
DESCRIPTOR.message_types_by_name['JinhuaRecRound'] = _JINHUARECROUND
DESCRIPTOR.message_types_by_name['JinhuaLookCardAction'] = _JINHUALOOKCARDACTION
DESCRIPTOR.message_types_by_name['JinhuaBetScoreAction'] = _JINHUABETSCOREACTION
DESCRIPTOR.message_types_by_name['JinhuaCompare'] = _JINHUACOMPARE
DESCRIPTOR.message_types_by_name['JinhuaPlayerOneSetResult'] = _JINHUAPLAYERONESETRESULT
DESCRIPTOR.message_types_by_name['JinhuaSettlePlayerInfo'] = _JINHUASETTLEPLAYERINFO
DESCRIPTOR.message_types_by_name['JinhuaReEnterPlayerInfo'] = _JINHUAREENTERPLAYERINFO
DESCRIPTOR.message_types_by_name['JinhuaRecordContent'] = _JINHUARECORDCONTENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JinhuaCreateRoom = _reflection.GeneratedProtocolMessageType('JinhuaCreateRoom', (_message.Message,), dict(
    DESCRIPTOR=_JINHUACREATEROOM,
    __module__='game.jinhua_pb2'
    # @@protoc_insertion_point(class_scope:JinhuaCreateRoom)
))
_sym_db.RegisterMessage(JinhuaCreateRoom)

JinhuaBankerConfirm = _reflection.GeneratedProtocolMessageType('JinhuaBankerConfirm', (_message.Message,), dict(
    DESCRIPTOR=_JINHUABANKERCONFIRM,
    __module__='game.jinhua_pb2'
    # @@protoc_insertion_point(class_scope:JinhuaBankerConfirm)
))
_sym_db.RegisterMessage(JinhuaBankerConfirm)

JinhuaRecRound = _reflection.GeneratedProtocolMessageType('JinhuaRecRound', (_message.Message,), dict(
    DESCRIPTOR=_JINHUARECROUND,
    __module__='game.jinhua_pb2'
    # @@protoc_insertion_point(class_scope:JinhuaRecRound)
))
_sym_db.RegisterMessage(JinhuaRecRound)

JinhuaLookCardAction = _reflection.GeneratedProtocolMessageType('JinhuaLookCardAction', (_message.Message,), dict(
    DESCRIPTOR=_JINHUALOOKCARDACTION,
    __module__='game.jinhua_pb2'
    # @@protoc_insertion_point(class_scope:JinhuaLookCardAction)
))
_sym_db.RegisterMessage(JinhuaLookCardAction)

JinhuaBetScoreAction = _reflection.GeneratedProtocolMessageType('JinhuaBetScoreAction', (_message.Message,), dict(
    DESCRIPTOR=_JINHUABETSCOREACTION,
    __module__='game.jinhua_pb2'
    # @@protoc_insertion_point(class_scope:JinhuaBetScoreAction)
))
_sym_db.RegisterMessage(JinhuaBetScoreAction)

JinhuaCompare = _reflection.GeneratedProtocolMessageType('JinhuaCompare', (_message.Message,), dict(
    DESCRIPTOR=_JINHUACOMPARE,
    __module__='game.jinhua_pb2'
    # @@protoc_insertion_point(class_scope:JinhuaCompare)
))
_sym_db.RegisterMessage(JinhuaCompare)

JinhuaPlayerOneSetResult = _reflection.GeneratedProtocolMessageType('JinhuaPlayerOneSetResult', (_message.Message,),
                                                                    dict(
                                                                        DESCRIPTOR=_JINHUAPLAYERONESETRESULT,
                                                                        __module__='game.jinhua_pb2'
                                                                        # @@protoc_insertion_point(class_scope:JinhuaPlayerOneSetResult)
                                                                    ))
_sym_db.RegisterMessage(JinhuaPlayerOneSetResult)

JinhuaSettlePlayerInfo = _reflection.GeneratedProtocolMessageType('JinhuaSettlePlayerInfo', (_message.Message,), dict(
    DESCRIPTOR=_JINHUASETTLEPLAYERINFO,
    __module__='game.jinhua_pb2'
    # @@protoc_insertion_point(class_scope:JinhuaSettlePlayerInfo)
))
_sym_db.RegisterMessage(JinhuaSettlePlayerInfo)

JinhuaReEnterPlayerInfo = _reflection.GeneratedProtocolMessageType('JinhuaReEnterPlayerInfo', (_message.Message,), dict(
    DESCRIPTOR=_JINHUAREENTERPLAYERINFO,
    __module__='game.jinhua_pb2'
    # @@protoc_insertion_point(class_scope:JinhuaReEnterPlayerInfo)
))
_sym_db.RegisterMessage(JinhuaReEnterPlayerInfo)

JinhuaRecordContent = _reflection.GeneratedProtocolMessageType('JinhuaRecordContent', (_message.Message,), dict(

    RecordPlayerContent=_reflection.GeneratedProtocolMessageType('RecordPlayerContent', (_message.Message,), dict(
        DESCRIPTOR=_JINHUARECORDCONTENT_RECORDPLAYERCONTENT,
        __module__='game.jinhua_pb2'
        # @@protoc_insertion_point(class_scope:JinhuaRecordContent.RecordPlayerContent)
    ))
    ,
    DESCRIPTOR=_JINHUARECORDCONTENT,
    __module__='game.jinhua_pb2'
    # @@protoc_insertion_point(class_scope:JinhuaRecordContent)
))
_sym_db.RegisterMessage(JinhuaRecordContent)
_sym_db.RegisterMessage(JinhuaRecordContent.RecordPlayerContent)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
