# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game/wuziqi.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='game/wuziqi.proto',
    package='',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x11game/wuziqi.proto\"%\n\x10WuziqiCreateRoom\x12\x11\n\tcountDown\x18\x01 \x01(\x05\"\xaf\x01\n\x18WuziqiPlayerOneSetResult\x12\x41\n\x07players\x18\x01 \x03(\x0b\x32\x30.WuziqiPlayerOneSetResult.WuziqiSettlePlayerInfo\x1aP\n\x16WuziqiSettlePlayerInfo\x12\x10\n\x08playerId\x18\x01 \x01(\x05\x12\x12\n\ntotalScore\x18\x02 \x01(\x05\x12\x10\n\x08\x61llPoint\x18\x03 \x01(\x05\x42\x02H\x03\x62\x06proto3')
)

_WUZIQICREATEROOM = _descriptor.Descriptor(
    name='WuziqiCreateRoom',
    full_name='WuziqiCreateRoom',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='countDown', full_name='WuziqiCreateRoom.countDown', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=21,
    serialized_end=58,
)

_WUZIQIPLAYERONESETRESULT_WUZIQISETTLEPLAYERINFO = _descriptor.Descriptor(
    name='WuziqiSettlePlayerInfo',
    full_name='WuziqiPlayerOneSetResult.WuziqiSettlePlayerInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='playerId', full_name='WuziqiPlayerOneSetResult.WuziqiSettlePlayerInfo.playerId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='totalScore', full_name='WuziqiPlayerOneSetResult.WuziqiSettlePlayerInfo.totalScore', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='allPoint', full_name='WuziqiPlayerOneSetResult.WuziqiSettlePlayerInfo.allPoint', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=156,
    serialized_end=236,
)

_WUZIQIPLAYERONESETRESULT = _descriptor.Descriptor(
    name='WuziqiPlayerOneSetResult',
    full_name='WuziqiPlayerOneSetResult',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='players', full_name='WuziqiPlayerOneSetResult.players', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_WUZIQIPLAYERONESETRESULT_WUZIQISETTLEPLAYERINFO, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=61,
    serialized_end=236,
)

_WUZIQIPLAYERONESETRESULT_WUZIQISETTLEPLAYERINFO.containing_type = _WUZIQIPLAYERONESETRESULT
_WUZIQIPLAYERONESETRESULT.fields_by_name['players'].message_type = _WUZIQIPLAYERONESETRESULT_WUZIQISETTLEPLAYERINFO
DESCRIPTOR.message_types_by_name['WuziqiCreateRoom'] = _WUZIQICREATEROOM
DESCRIPTOR.message_types_by_name['WuziqiPlayerOneSetResult'] = _WUZIQIPLAYERONESETRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WuziqiCreateRoom = _reflection.GeneratedProtocolMessageType('WuziqiCreateRoom', (_message.Message,), dict(
    DESCRIPTOR=_WUZIQICREATEROOM,
    __module__='game.wuziqi_pb2'
    # @@protoc_insertion_point(class_scope:WuziqiCreateRoom)
))
_sym_db.RegisterMessage(WuziqiCreateRoom)

WuziqiPlayerOneSetResult = _reflection.GeneratedProtocolMessageType('WuziqiPlayerOneSetResult', (_message.Message,),
                                                                    dict(

                                                                        WuziqiSettlePlayerInfo=_reflection.GeneratedProtocolMessageType(
                                                                            'WuziqiSettlePlayerInfo',
                                                                            (_message.Message,), dict(
                                                                                DESCRIPTOR=_WUZIQIPLAYERONESETRESULT_WUZIQISETTLEPLAYERINFO,
                                                                                __module__='game.wuziqi_pb2'
                                                                                # @@protoc_insertion_point(class_scope:WuziqiPlayerOneSetResult.WuziqiSettlePlayerInfo)
                                                                            ))
                                                                        ,
                                                                        DESCRIPTOR=_WUZIQIPLAYERONESETRESULT,
                                                                        __module__='game.wuziqi_pb2'
                                                                        # @@protoc_insertion_point(class_scope:WuziqiPlayerOneSetResult)
                                                                    ))
_sym_db.RegisterMessage(WuziqiPlayerOneSetResult)
_sym_db.RegisterMessage(WuziqiPlayerOneSetResult.WuziqiSettlePlayerInfo)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
