# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/mission.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='service/mission.proto',
    package='mahjong',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x15service/mission.proto\x12\x07mahjong\"\xd7\x01\n\x19RecUpdateMisssionProgress\x12=\n\x05\x64\x61tas\x18\x01 \x03(\x0b\x32..mahjong.RecUpdateMisssionProgress.MissionData\x1a{\n\x0bMissionData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0b\n\x03num\x18\x03 \x01(\x05\x12\x0e\n\x06maxNum\x18\x04 \x01(\x05\x12\x14\n\x0c\x63urrencyType\x18\x05 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x06 \x01(\x05\x12\r\n\x05state\x18\x07 \x01(\x05\"*\n\x1cReqGetMisssionProgressReward\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\x1cRecGetMisssionProgressReward\x12\r\n\x05state\x18\x01 \x01(\x05\x42\x36H\x03Z\x1cgame/message/mission;mission\xaa\x02\x13\x43huangMi.Mission.V1b\x06proto3')
)

_RECUPDATEMISSSIONPROGRESS_MISSIONDATA = _descriptor.Descriptor(
    name='MissionData',
    full_name='mahjong.RecUpdateMisssionProgress.MissionData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='mahjong.RecUpdateMisssionProgress.MissionData.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='type', full_name='mahjong.RecUpdateMisssionProgress.MissionData.type', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='num', full_name='mahjong.RecUpdateMisssionProgress.MissionData.num', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='maxNum', full_name='mahjong.RecUpdateMisssionProgress.MissionData.maxNum', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='currencyType', full_name='mahjong.RecUpdateMisssionProgress.MissionData.currencyType', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='currency', full_name='mahjong.RecUpdateMisssionProgress.MissionData.currency', index=5,
            number=6, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='state', full_name='mahjong.RecUpdateMisssionProgress.MissionData.state', index=6,
            number=7, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=127,
    serialized_end=250,
)

_RECUPDATEMISSSIONPROGRESS = _descriptor.Descriptor(
    name='RecUpdateMisssionProgress',
    full_name='mahjong.RecUpdateMisssionProgress',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='datas', full_name='mahjong.RecUpdateMisssionProgress.datas', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_RECUPDATEMISSSIONPROGRESS_MISSIONDATA, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=35,
    serialized_end=250,
)

_REQGETMISSSIONPROGRESSREWARD = _descriptor.Descriptor(
    name='ReqGetMisssionProgressReward',
    full_name='mahjong.ReqGetMisssionProgressReward',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='mahjong.ReqGetMisssionProgressReward.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=252,
    serialized_end=294,
)

_RECGETMISSSIONPROGRESSREWARD = _descriptor.Descriptor(
    name='RecGetMisssionProgressReward',
    full_name='mahjong.RecGetMisssionProgressReward',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='state', full_name='mahjong.RecGetMisssionProgressReward.state', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=296,
    serialized_end=341,
)

_RECUPDATEMISSSIONPROGRESS_MISSIONDATA.containing_type = _RECUPDATEMISSSIONPROGRESS
_RECUPDATEMISSSIONPROGRESS.fields_by_name['datas'].message_type = _RECUPDATEMISSSIONPROGRESS_MISSIONDATA
DESCRIPTOR.message_types_by_name['RecUpdateMisssionProgress'] = _RECUPDATEMISSSIONPROGRESS
DESCRIPTOR.message_types_by_name['ReqGetMisssionProgressReward'] = _REQGETMISSSIONPROGRESSREWARD
DESCRIPTOR.message_types_by_name['RecGetMisssionProgressReward'] = _RECGETMISSSIONPROGRESSREWARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecUpdateMisssionProgress = _reflection.GeneratedProtocolMessageType('RecUpdateMisssionProgress', (_message.Message,),
                                                                     dict(

                                                                         MissionData=_reflection.GeneratedProtocolMessageType(
                                                                             'MissionData', (_message.Message,), dict(
                                                                                 DESCRIPTOR=_RECUPDATEMISSSIONPROGRESS_MISSIONDATA,
                                                                                 __module__='service.mission_pb2'
                                                                                 # @@protoc_insertion_point(class_scope:mahjong.RecUpdateMisssionProgress.MissionData)
                                                                             ))
                                                                         ,
                                                                         DESCRIPTOR=_RECUPDATEMISSSIONPROGRESS,
                                                                         __module__='service.mission_pb2'
                                                                         # @@protoc_insertion_point(class_scope:mahjong.RecUpdateMisssionProgress)
                                                                     ))
_sym_db.RegisterMessage(RecUpdateMisssionProgress)
_sym_db.RegisterMessage(RecUpdateMisssionProgress.MissionData)

ReqGetMisssionProgressReward = _reflection.GeneratedProtocolMessageType('ReqGetMisssionProgressReward',
                                                                        (_message.Message,), dict(
        DESCRIPTOR=_REQGETMISSSIONPROGRESSREWARD,
        __module__='service.mission_pb2'
        # @@protoc_insertion_point(class_scope:mahjong.ReqGetMisssionProgressReward)
    ))
_sym_db.RegisterMessage(ReqGetMisssionProgressReward)

RecGetMisssionProgressReward = _reflection.GeneratedProtocolMessageType('RecGetMisssionProgressReward',
                                                                        (_message.Message,), dict(
        DESCRIPTOR=_RECGETMISSSIONPROGRESSREWARD,
        __module__='service.mission_pb2'
        # @@protoc_insertion_point(class_scope:mahjong.RecGetMisssionProgressReward)
    ))
_sym_db.RegisterMessage(RecGetMisssionProgressReward)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b(
    'H\003Z\034game/message/mission;mission\252\002\023ChuangMi.Mission.V1'))
# @@protoc_insertion_point(module_scope)
