# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/signin.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='service/signin.proto',
    package='mahjong',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x14service/signin.proto\x12\x07mahjong\"!\n\x0eReqGetSignInfo\x12\x0f\n\x07\x61llocId\x18\x01 \x01(\x05\"<\n\x0eRecGetSignInfo\x12\r\n\x05state\x18\x01 \x01(\x08\x12\r\n\x05\x63ombo\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\x05\"\x1c\n\tReqSignIn\x12\x0f\n\x07\x61llocId\x18\x01 \x01(\x05\"\x1a\n\tRecSignIn\x12\r\n\x05state\x18\x01 \x01(\x08\x42.H\x03Z\x15message/signin;signin\xaa\x02\x12\x43huangMi.Signin.V1b\x06proto3')
)

_REQGETSIGNINFO = _descriptor.Descriptor(
    name='ReqGetSignInfo',
    full_name='mahjong.ReqGetSignInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='allocId', full_name='mahjong.ReqGetSignInfo.allocId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=33,
    serialized_end=66,
)

_RECGETSIGNINFO = _descriptor.Descriptor(
    name='RecGetSignInfo',
    full_name='mahjong.RecGetSignInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='state', full_name='mahjong.RecGetSignInfo.state', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='combo', full_name='mahjong.RecGetSignInfo.combo', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='time', full_name='mahjong.RecGetSignInfo.time', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=68,
    serialized_end=128,
)

_REQSIGNIN = _descriptor.Descriptor(
    name='ReqSignIn',
    full_name='mahjong.ReqSignIn',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='allocId', full_name='mahjong.ReqSignIn.allocId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=130,
    serialized_end=158,
)

_RECSIGNIN = _descriptor.Descriptor(
    name='RecSignIn',
    full_name='mahjong.RecSignIn',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='state', full_name='mahjong.RecSignIn.state', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=160,
    serialized_end=186,
)

DESCRIPTOR.message_types_by_name['ReqGetSignInfo'] = _REQGETSIGNINFO
DESCRIPTOR.message_types_by_name['RecGetSignInfo'] = _RECGETSIGNINFO
DESCRIPTOR.message_types_by_name['ReqSignIn'] = _REQSIGNIN
DESCRIPTOR.message_types_by_name['RecSignIn'] = _RECSIGNIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqGetSignInfo = _reflection.GeneratedProtocolMessageType('ReqGetSignInfo', (_message.Message,), dict(
    DESCRIPTOR=_REQGETSIGNINFO,
    __module__='service.signin_pb2'
    # @@protoc_insertion_point(class_scope:mahjong.ReqGetSignInfo)
))
_sym_db.RegisterMessage(ReqGetSignInfo)

RecGetSignInfo = _reflection.GeneratedProtocolMessageType('RecGetSignInfo', (_message.Message,), dict(
    DESCRIPTOR=_RECGETSIGNINFO,
    __module__='service.signin_pb2'
    # @@protoc_insertion_point(class_scope:mahjong.RecGetSignInfo)
))
_sym_db.RegisterMessage(RecGetSignInfo)

ReqSignIn = _reflection.GeneratedProtocolMessageType('ReqSignIn', (_message.Message,), dict(
    DESCRIPTOR=_REQSIGNIN,
    __module__='service.signin_pb2'
    # @@protoc_insertion_point(class_scope:mahjong.ReqSignIn)
))
_sym_db.RegisterMessage(ReqSignIn)

RecSignIn = _reflection.GeneratedProtocolMessageType('RecSignIn', (_message.Message,), dict(
    DESCRIPTOR=_RECSIGNIN,
    __module__='service.signin_pb2'
    # @@protoc_insertion_point(class_scope:mahjong.RecSignIn)
))
_sym_db.RegisterMessage(RecSignIn)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
                                                _b('H\003Z\025message/signin;signin\252\002\022ChuangMi.Signin.V1'))
# @@protoc_insertion_point(module_scope)
