# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/gateway.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='base/gateway.proto',
    package='',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x12\x62\x61se/gateway.proto\".\n\x0eGateWayMessage\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42 \n\x1a\x63om.cmsy.majong.mode.protoH\x03P\x00\x62\x06proto3')
)

_GATEWAYMESSAGE = _descriptor.Descriptor(
    name='GateWayMessage',
    full_name='GateWayMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='userId', full_name='GateWayMessage.userId', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='data', full_name='GateWayMessage.data', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=22,
    serialized_end=68,
)

DESCRIPTOR.message_types_by_name['GateWayMessage'] = _GATEWAYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GateWayMessage = _reflection.GeneratedProtocolMessageType('GateWayMessage', (_message.Message,), dict(
    DESCRIPTOR=_GATEWAYMESSAGE,
    __module__='base.gateway_pb2'
    # @@protoc_insertion_point(class_scope:GateWayMessage)
))
_sym_db.RegisterMessage(GateWayMessage)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
                                                _b('\n\032com.cmsy.majong.mode.protoH\003P\000'))
# @@protoc_insertion_point(module_scope)
